create table tb_product (
    id bigint generated by default as identity,
    name varchar(255),
    price float(53),
    quantity integer,
    unit_measure smallint check (unit_measure between 0 and 2),
    category_id bigint,
    primary key (id),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES tb_category(id)
    );