create table tb_provider (
    id bigint generated by default as identity,
    name varchar(255),
    cnpj varchar(255) unique,
    email varchar(255) unique,
    phone varchar(255),
    active boolean,
    primary key (id)
    );