create table tb_client (
    id bigint generated by default as identity,
    name varchar(255),
    cpf_cnpj varchar(255) not null,
    address varchar(255),
    phone varchar(255),
    register_date date,
    primary key (id)
    );