create table tb_stock_movement (
    id bigint generated by default as identity,
    moment TIMESTAMP WITHOUT TIME ZONE,
    quantity integer,
    type smallint check (type between 0 and 1),
    reason TEXT,
    product_id bigint not null,
    user_id bigint not null,
    client_id bigint,
    provider_id bigint,
    primary key (id),
    CONSTRAINT fk_stock_product FOREIGN KEY (product_id) REFERENCES tb_product(id),
    CONSTRAINT fk_stock_user FOREIGN KEY (user_id) REFERENCES tb_user(id),
    CONSTRAINT fk_stock_client FOREIGN KEY (client_id) REFERENCES tb_client(id),
    CONSTRAINT fk_stock_provider FOREIGN KEY (provider_id) REFERENCES tb_provider(id)
    );